### ISSUE TITLE
关系图可拖动范围太小

### ISSUE THREAD

**Issue by sorzero79** [88250/liandi#107]
### 描述问题

关系图可拖动范围太小，只有图的位置可以拖动，外围的空白处无法拖动。

### 期待的结果

建议增大拖动的交互区，在整个关系图窗口中都能响应拖动操作。

**Comment by 88250** [comment]
> 建议关系图做成和设置面板一样的浮动面板。
目前笔记量稍大就要拉开关系图窗口才能展示全，而直接挤占了编辑区，影响使用

**Comment by 88250** [comment]
将在 https://github.com/88250/liandi/issues/108 中统一重做窗口布局系统。
