### ISSUE TITLE
改进一下文件操作

### ISSUE THREAD

**Issue by chinnux** [88250/liandi#109]
### 文件操作不方便
1. 新建文件最好有快捷键
2. 可以手动保存，文件改变了，标题栏的文件名后面可以以“*”提示，和Typora一样
3. 增加另存为选项

**Comment by 88250** [comment]
1. 快捷键后续在 https://github.com/88250/liandi/issues/120 中实现
2. https://github.com/88250/liandi/issues/121
3. 导出以后做

感谢反馈！
