### ISSUE TITLE
搜索、关系图、块链中引用节点文本丢失

### ISSUE THREAD

**Issue by 88250** [88250/liandi#111]
![image](https://user-images.githubusercontent.com/873584/90213587-c6960500-de28-11ea-9520-59925232d317.png)

**Comment by zhaojiansong** [comment]
Bug one:
新添加的链接不能显示在右侧
![WA8)DT$MR}6$66A}3BZ $UT](https://user-images.githubusercontent.com/25213926/90220770-6a88ac00-de3b-11ea-8d4a-5587cf44cb72.jpg)

Bug two:
右侧关系图莫名丢失

![Bug1](https://user-images.githubusercontent.com/25213926/90220694-475dfc80-de3b-11ea-9858-d4c6df2b60e0.gif)

**Comment by 88250** [comment]
@zhaojiansong 收到

**Comment by 88250** [comment]
@zhaojiansong 这两个问题请关注 https://github.com/88250/liandi/issues/92
