### ISSUE TITLE
关系图使用问题

### ISSUE THREAD

**Issue by wfan14513** [88250/liandi#112]
链滴的关系图，只有根块显示名称，因此，第一眼，我只能知道有很多内容连接到这个知识点，但是其它块没显示名称或主题，必须把鼠标移动到那个点上才知道具体是什么内容。

带来的问题一：不直观，影响思考；
问题二：移到那个点以后，高亮的链接关系变了，变成以这个点为主了，思路就被打断了。必须回到之前的点，再去找其它相关链接看具体是什么内容。

整个过程中，注意力被不断打断和切换，非常影响思考。

希望改善！

**Comment by 88250** [comment]
收到，问题一是因为子块内容比较长，如果展示内容的话整个图会太乱了，这方面有什么建议吗？问题二我们再优化一下，谢谢反馈。

**Comment by wfan14513** [comment]
问题二的话，是不是能够点击某个点，固定链接联系。
问题一的话，每个块，或者卡片笔记，因为都不会太大，所以一定是有个主题的或者关键字（其实某个角度就相当于标签了），能有办法显示这个主题或者关键字就行。否则关系图就失去意义了。

比方说，我的根块是《如何减肥？》，链接到《节制饮食》，链接到《健身》，等等等等，这样就比较直观了。

其实，我能理解你说的 抽象泄露 概念，但是知识的表现，在使用过程中，一定是具体到某个形式的，比如说，一般人会说“请拿双**筷子**给我”，而不会说“请拿双**木棍**给我”。这是我个人的一点粗浅理解。

**Comment by 88250** [comment]
@wfan14513 问题二会优化的。看来问题一是用法问题，如果把文档当做小卡片使用的话，其实就没有这个问题了，文档标题已经定义。

**Comment by wfan14513** [comment]
嗯，如果是块引，看能不能类似跳出个框，输入在关系图中要显示的信息等等。

**Comment by 88250** [comment]
@wfan14513 有点不懂了，需要细节，谢谢。

**Comment by wfan14513** [comment]
我的想法是，就是关系图中的那些“线”，鼠标放上去的时候，能不能显示类似思维导图中的“标注”信息。

画思维导图，是个不错的学习过程，比如，你看一篇文章，教你《怎么练胸肌》。要“练上胸”，用【上斜卧推】，要“练中胸”，用【平板卧推】，要“练下胸”，用【双杠臂屈伸】，等等。用思维导图整理，学习，记忆。

而用双链笔记软件学习，则是另一种学习过程：
1.某一天，我看一篇文章《为什么肩部三角肌前束不用练》，里面说【上斜卧推】是“练上胸”的，但是会练到三角肌前束；另外一天，我看到《有哪些必练的复合动作》，里面说【平板卧推】是“练中胸”的王牌动作；又一天，我看到《如果练出麒麟臂》，里面说【双杠臂屈伸】是练肱三头肌的，但是也是很好的“练下胸”的动作。
2.【上斜卧推】，【平板卧推】，【双杠臂屈伸】都是“点”，共同链接到【练胸肌】，链接逻辑（即标注）分别是“练上胸”，“练中胸”和“练下胸”。
3.随着不断学习，【练胸肌】这个点越来越大越来越明显，就形成了一个完整的知识点，我可以写一篇文章吹NB，可以开课教别人，等等等等。
[示意图](https://cdn.jsdelivr.net/gh/wfan14513/PublicPic01/%E5%8F%8C%E9%93%BE%E7%AC%94%E8%AE%B0%E5%AD%A6%E4%B9%A0%E8%BF%87%E7%A8%8B%E7%A4%BA%E6%84%8F%E5%9B%BE.png)

**Comment by 88250** [comment]
@wfan14513 我理解下来是这样的：你想用某些内容来补充某个内容，随着补充内容的不断增加，被补充的内容就会不断丰富。这个过程是递归的，每个内容都可以被其他内容不断补充。

我应该没理解错吧……如果是这样，你把上面描述的“内容”两个字换成“内容块”看下应该也没问题，那么现在的问题就是如何补充内容块，其实只需要在内容块中逐渐引用其他内容块就行了，引入的块越多，自身块的内容也就越多。
