### ISSUE TITLE
目录序号排序

### ISSUE THREAD

**Issue by DarnellChen** [88250/liandi#113]
### 你在什么场景下需要该功能？

在编写或阅读部分md书本文件夹时

### 描述可能的解决方案

可以像windows文件夹实现文件按数字大小排序

![image](https://user-images.githubusercontent.com/26782544/90231191-5ea5e580-de4d-11ea-8e52-d659a15a1b58.png)
![image](https://user-images.githubusercontent.com/26782544/90231216-682f4d80-de4d-11ea-9e67-1d5f43c69f63.png)

**Comment by 88250** [comment]
已经记录，请关注 https://github.com/88250/liandi/issues/113
