### ISSUE TITLE
文章内部块的引用

### ISSUE THREAD

**Issue by lyslives** [88250/liandi#118]
### 你在什么场景下需要该功能？
现有块引用基本引用外部文章的块。能否引用本文中已有的块？

### 描述可能的解决方案

请尽量清晰精准地描述你期待我们要做的，描述你想到的实现方案。

### 描述你认为的候选方案

请尽量清晰精准地描述你能接受的候选解决方案。

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by 88250** [comment]
可以引用当前文档的块的，只是不能引用当前正在输入的块。引用前需要手动保存一下文档，这样块索引才能构建好，后面才能引用。
