### ISSUE TITLE
MD中**MD**不能正确显示。

### ISSUE THREAD

**Issue by lyslives** [88250/liandi#126]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

有完整标注，无论手工还是选点，在这种情况下，不能修饰成粗体。

https://cdn.jsdelivr.net/gh/lyslives/pic/lyslives/pic/herbal/mmexport1597540243211.jpg

**Comment by 88250** [comment]
麻烦给一下 md 原文。

**Comment by lyslives** [comment]
这是我从lidandi导出的文档，您看看哈。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: D<mailto:notifications@github.com>
发送时间: 2020年8月16日 9:30
收件人: 88250/liandi<mailto:liandi@noreply.github.com>
抄送: lyslives<mailto:lyslives@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [88250/liandi] MD中**MD**不能正确显示。 (#126)


麻烦给一下 md 原文。

―

**Comment by 88250** [comment]
不好意思，没有看到下载地址。

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/90330549-2be02680-dfe0-11ea-9623-efbcbdab9065.png)

解析没有问题的，这是标准 md 语法规定的。https://spec.commonmark.org/dingus/
