### ISSUE TITLE
标题块

### ISSUE THREAD

**Issue by 88250** [88250/liandi#150]
Markdown 规范中定义标题是一种块级元素，但实际使用时标题往往是作为块级容器的，标题应该涵盖下面的内容块，直到下一个同级标题打断。

实现上和[大纲折叠](https://github.com/Vanessa219/vditor/issues/479)算法一致。

**Comment by jazzson** [comment]
建议加入标题后，可以在图谱中显示标题名称和同名称块数量，这样的用法很实用

**Comment by 88250** [comment]
@jazzson 这个特性还在考虑。如果现在就有标题块的需求，可以用拆分文档来实现。

**Comment by 88250** [comment]
经过考虑，标题块的引入反而会增加概念，也不符合 Markdown 的语法，手动拆分文档是较为稳妥的做法。
