### ISSUE TITLE
Double shift快捷键可以自设吗？

### ISSUE THREAD

**Issue by Mrs-jiyeon** [88250/liandi#164]
写文档时，中英文之间的来回切换靠单点shift来进行切换的，很多情况下会因为没有注意到当前的输入法是英文还是中文，导致一次shift之后的输入法切换到不到，需要再点击一次。经常性的会唤起搜索弹窗，这个快捷键可否自己设置。

**Comment by 88250** [comment]
你好，暂时没有自定义快捷键，后面会支持，感谢反馈。

**Comment by Vanessa219** [comment]
可关注 https://github.com/88250/liandi/issues/120
