### ISSUE TITLE
windows下打开文件夹位置如果为win默认的文档地址，检索不到内部文件

### ISSUE THREAD

**Issue by Mrs-jiyeon** [88250/liandi#166]
[gif图演示](https://lwbx.org.cn/liandi.gif) 如题，可查看git具体操作

**Comment by 88250** [comment]
你好，我这里不能重现。请看下链滴笔记的日志，在 ~/.liandi/ 路径下。

**Comment by 88250** [comment]
先关闭了，有额外信息请继续跟帖。

**Comment by wangfh5** [comment]
我感觉我也有类似的问题，挂载一个位于“C盘的下载文件夹”中的文件夹之后显示不出来这个文档



> [gif图演示](https://lwbx.org.cn/liandi.gif) 如题，可查看git具体操作
