### ISSUE TITLE
自定义模板功能，卡片式笔记法必备功能。

### ISSUE THREAD

**Issue by wfan14513** [88250/liandi#174]
### 你在什么场景下需要该功能？

请尽量清晰精准地描述你碰到的问题。

### 描述可能的解决方案

请尽量清晰精准地描述你期待我们要做的，描述你想到的实现方案。

### 描述你认为的候选方案

请尽量清晰精准地描述你能接受的候选解决方案。

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by 88250** [comment]
你好，请详述。

**Comment by wfan14513** [comment]
因为现在各种笔记或者记卡片的方法有很多，比如，我可以自建一个“康奈尔笔记法格式”的模板，需要的时候，新建文档可以直接根据模板新建。

**Comment by wfan14513** [comment]
不好意思，因为开github很慢很慢，所以描述都省略了，或者尽量简短了。

**Comment by 88250** [comment]
不好意思，我没有看明白，先关闭了。欢迎继续跟帖讨论。
