### ISSUE TITLE
请帮助支持内容剪切生成新文档

### ISSUE THREAD

**Issue by jazzson** [88250/liandi#176]
### 你在什么场景下需要该功能？

在阅读过程中，需要跨越markdown 块定义规则生成内容块的时候。需要把选中内容剪切出来，自动插入到一个新文档中

### 描述可能的解决方案

1、用户选中需要剪切到新文档的内容
2、调用快捷键
     a、剪切选中的内容
     b、自动创建一个新文档
     c、把剪切的内容粘贴到新文档中
     d、返回原来的阅读位置

### 描述你认为的候选方案

请尽量清晰精准地描述你能接受的候选解决方案。

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by 88250** [comment]
手动剪切？

**Comment by wangfh5** [comment]
这是想同时引用多个块，甚至引用某个块的一部分？同时引用多个块，我觉得在一定使用场景下，标题块是不错的解决方式；一般地，感觉这个剪贴类似于蚕大给obsidian写的quicker动作“选文引块”

**Comment by jazzson** [comment]
这主要使用在拆分文档的场景下使用。我原先在ob 下，直接用大纲模式写了不少文档。现在想把他们拆分成块，然后重新进行整理。所以需要蚕大给obsidian写的quicker动作“选文引块”

**Comment by 88250** [comment]
我觉得还是由用户手动拆分文档比较妥当，原因请看 #150。
