### ISSUE TITLE
1.1.4 / 1.1.6 : can't browse folders/files and preferences not saved after first run

### ISSUE THREAD

**Issue by cannibalox** [88250/liandi#186]
Hi, sorry if it's not relevant, I don't speak chinese so I use google translate...

### 描述问题

I run into multiple issues with 1.1.6, windows 10 Enterprise LTSC1809 17763.347:
* since 1.1.4, it's not possible to open folders/files or create a new doc (tested with 1.1.4 and 1.1.6), it was working with 1.1.3 (and 1.1.2)
* Maybe a problem with saving preferences : 
    * on the first start of Liandi (1.1.6 fresh install, cleaned users\xxx\.liandi) : you can change language or theme color. 
    * On the second start, it's not possible to change settings anymore. 

### 重现步骤

请描述如何重现这个问题：

1. open Liandi.exe 
2. Click on 'Open Local Notebook` and pick a folder
3. the root folder shows up, it can unfold one level of subfolder, but not deeper and no files are shown (only top level folder and 1 level subfolder) 
4. then click 'New Doc`
5. the popup appears, type a title for the doc 
6. it's not possible to validate/confirm or create the document

### 期待的结果 expected result

* when clicking on the folder the folder should unfold and list all files and subfolders within.
* preferences should be saved 

### 截屏或录像 / videos

videos illustrating the problem (using the same folder with markdown files in the 3 videos), fresh installs (deleted conf.json between each try)

liandi 1.1.6 : fresh install then restarting 2 times, preferences not saved, can't browse folder
![Imgur](https://i.imgur.com/iftcii0.gif)

liandi 1.1.4 : fresh install, can't browse folder
![Imgur](https://imgur.com/Dy90zHw.gif)

liandi 1.1.3 : working 
![Imgur](https://imgur.com/7G9v9jJ.gif)

log:  for the second video liandi 1.1.4
```
I 2020/08/27 23:16:19 log.go:58: 运行模式 [prod]
D 2020/08/27 23:16:19 conf.go:69: 加载配置文件 [C:\Users\phi\.liandi\conf.json] 完毕
I 2020/08/27 23:16:19 main.go:127: 内核进程 [v1.1.4] 正在启动 [C:\_ppApps\_write\Liandi pkm\Liandi 1.1.4]，监听端口 [http://127.0.0.1:6806]
D 2020/08/27 23:16:19 conf.go:294: 开始导入笔记本 [http://127.0.0.1:6807/webdav/ov21alq/liandi/] 下新的 Markdown 文件
D 2020/08/27 23:16:20 main.go:99: request [{"cmd":"getconf","reqId":1598562980250,"param":{}}]
```

### 桌面端环境 

- OS: : windows 10 LTSC 1809, system in english, using french keyboard
- Browser : chrome 84 / firefox 78.0.2
- Liandi 1.1.2 / 1.1.3 / 1.1.4 / 1.1.6 (deleted  users\xxx\.liandi\conf.json between each test)

### 其他信息

Maybe you already know the issues, anyway Liandi is a very interesting project 👍

**Comment by 88250** [comment]
Thanks for your feedback, it is a known bug, we will fix it in v1.1.7.

**Comment by cannibalox** [comment]
thank you. should I report issues here in the future or is there another channel I should use ?

**Comment by 88250** [comment]
Just here.

**Comment by cannibalox** [comment]
ok thanks I close
