### ISSUE TITLE
动态文件监控设计建议

### ISSUE THREAD

**Issue by HaujetZhao** [88250/liandi#189]
现在的文档元数据都在一个 json 文件里存储，但如果 md 文件被其它编辑器更改，或者在其它同步设备上更改后，同步到本地，这些更改就无法呈现在 json 文件中。所以 json 文件中要记录 md 文件最后一次修改的信息，当发现修改时间不同，将 md 文件中的新变化同步到 json 中

**Comment by 88250** [comment]
在外部修改 md 不会重新“导入”，因为块的映射关系可能会发生不可预知的变化。这是技术原理问题，实现不了……
