### ISSUE TITLE
支持本地绝对路径渲染图片

### ISSUE THREAD

**Issue by geektomya** [88250/liandi#34]
我用链滴打开我之前用typora写的文档，发现图片（在本地）加载不出来。然后看了下时因为使用的`![]()`语法问题，但是可以用该语法加载网络图片。但是可以用`<img src=本地图片地址>`加载本地图片。问题如下图所示：
![2](https://user-images.githubusercontent.com/34698026/75600217-ba6ef300-5ae7-11ea-988a-1555d8b175da.png)

**Comment by 88250** [comment]
图片本地路径是和当前的 test.md 在同一个目录下吗？

**Comment by geektomya** [comment]
> 图片本地路径是和当前的 test.md 在同一个目录下吗？

是的，我刚又尝试了（win系统下）一下。图片和文档在同一目录下，使用相对路径可以加载，使用绝对路径不可以加载。然后图片和目录不在同一目录下，好像怎么都不可以加载。

**Comment by 88250** [comment]
绝对路径指的是 `file://` 开头那种么？麻烦贴一下完整的 Markdown 文本还有目录结构截图。

**Comment by geektomya** [comment]
> 绝对路径指的是 `file://` 开头那种么？麻烦贴一下完整的 Markdown 文本还有目录结构截图。

是的。
目录如下
![11](https://user-images.githubusercontent.com/34698026/75600455-834e1100-5aea-11ea-9bed-de75c2024288.png)
t'ytypora打开如下
![22](https://user-images.githubusercontent.com/34698026/75600458-8943f200-5aea-11ea-9a2b-6538889aece9.png)
这时使用链滴就会打不开图片
----------------------
刚看了一下，linux下都是正常的。

**Comment by 88250** [comment]
所以总结一下问题就是：不能使用本地绝对路径渲染图片。这个问题稍后修复，感谢反馈！

**Comment by geektomya** [comment]
> 所以总结一下问题就是：不能使用本地绝对路径渲染图片。这个问题稍后修复，感谢反馈！

对，但是只有win下有这个情况耶，Linux不存在。嘻嘻，尽点薄力，D大加油，你们的产品的体验都挺好的~~

**Comment by 88250** [comment]
已经修复，稍后发布 v0.1.3。
