### ISSUE TITLE
Double Shift 快捷键容易误触

### ISSUE THREAD

**Issue by ghostsf** [88250/liandi#45]
### 描述问题

Double Shift 快捷键容易误触，切换输入法等操作容易触发，影响使用

### 期待的结果

能否自定义快捷键

**Comment by 88250** [comment]
你用的版本时 v0.1.3 么？如果是的话应该修[复过一次](https://github.com/88250/liandi/issues/45)。如果是这个版本但还又问题，说明那次修复效果不太好，稍后我们再优化看看。

短期内应该不会支持自定义快捷键，感谢反馈了。

**Comment by ghostsf** [comment]
> 你用的版本时 v0.1.3 么？如果是的话应该修[复过一次](https://github.com/88250/liandi/issues/45)。如果是这个版本但还又问题，说明那次修复效果不太好，稍后我们再优化看看。
> 
> 短期内应该不会支持自定义快捷键，感谢反馈了。

是 v0.1.3

**Comment by 88250** [comment]
收到，下个版本会继续进行优化。
