### ISSUE TITLE
增加 Setext 标题解析开关

### ISSUE THREAD

**Issue by ghostsf** [88250/liandi#46]
### 描述问题

分隔符用`---`写的时候，切换一次模式，所见即所得<->编辑&预览，会发现原来的`---`被改写了，变成`--------------`或者更多`-`。

### 期待的结果

切换模式不影响原markdown内容。

**Comment by 88250** [comment]
方便录个动画重现一下问题么？我这里没能重现。

![f](https://user-images.githubusercontent.com/873584/78042706-fcb87800-73a4-11ea-8af0-db1c48b1816b.gif)

**Comment by 88250** [comment]
请下载最新版再试试，我先关闭了。

**Comment by ghostsf** [comment]
没注意看消息。
mac os，0.1.3
可以复现。

![image](https://user-images.githubusercontent.com/9978816/78665100-db590e00-7907-11ea-972b-7e96bd40b686.png)

**Comment by ghostsf** [comment]
![Kapture 2020-04-07 at 19 39 11](https://user-images.githubusercontent.com/9978816/78665399-55899280-7908-11ea-9b02-518736279227.gif)

@88250

**Comment by Vanessa219** [comment]
这个分隔符在切换的时候做了格式化，长度和标题长度一直

**Comment by ghostsf** [comment]
> 这个分隔符在切换的时候做了格式化，长度和标题长度一直

额，这个不用格式化吧。三个就可以表示分隔了。

**Comment by 88250** [comment]
@ghostsf 这不是分隔线语法，这是 [Setext 标题](https://hacpai.com/article/1583129520165#%E6%A0%87%E9%A2%98%E5%8F%AF%E9%80%89%E8%AF%AD%E6%B3%95)语法哦。

**Comment by ghostsf** [comment]
额，好吧。
之前导了些hexo的md文件，其Front-matter要---分隔，一切换，就变了。

**Comment by 88250** [comment]
这样吧，我们加个配置项，是否解析 Setext 标题，关闭 Setext 解析的话会解析为分隔线，这样就能兼容了。

**Comment by ghostsf** [comment]
Ok






在2020年04月07日 20:09，D 写道：

这样吧，我们加个配置项，是否解析 Setext 标题，关闭 Setext 解析的话会解析为分隔线，这样就能兼容了。
