### ISSUE TITLE
Markdown 细节配置

### ISSUE THREAD

**Issue by 88250** [88250/liandi#5]
* 是否启用脚注支持
* 是否启用 [ToC] 支持
* 是否需要中西文间自动插入空格
* 是否进行自动术语修正
* 中文后跟英文逗号句号等标点是否自动替换为中文对应标点
* 内联数学公式是否允许起始 $ 后紧跟数字
* 数学公式引擎切换 MathJax、Ketax

**Comment by Vanessa219** [comment]
已完成 

* 是否需要中西文间自动插入空格
* 是否进行自动术语修正
* 中文后跟英文逗号句号等标点是否自动替换为中文对应标点
* 内联数学公式是否允许起始 $ 后紧跟数字
* 数学公式引擎切换 MathJax、Ketax

其余需要 lute 和 vditor 支持

**Comment by 88250** [comment]
* 是否启用脚注支持
* 是否启用 [ToC] 支持

放到后续版本中实现吧。
