### ISSUE TITLE
支持vi编辑

### ISSUE THREAD

**Issue by chenyansong1** [88250/liandi#55]
### 你在什么场景下需要该功能？

请尽量清晰精准地描述你碰到的问题。

### 描述可能的解决方案

请尽量清晰精准地描述你期待我们要做的，描述你想到的实现方案。

### 描述你认为的候选方案

请尽量清晰精准地描述你能接受的候选解决方案。

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by 88250** [comment]
感谢反馈，编辑器用的是 [Vditor](https://github.com/Vanessa219/vditor)，暂时没有这方面的计划，我先关闭了。
