### ISSUE TITLE
Add language config option in the first screen

### ISSUE THREAD

**Issue by jakekwak** [88250/liandi#58]
setting: language, default directory or webdav link etc
![52](https://user-images.githubusercontent.com/15811943/81522611-be519980-9310-11ea-8b2f-0eb2cc3c5606.png)

**Comment by 88250** [comment]
Thanks for your advice, we can add a language config option before the current first screen. 

@Vanessa219

**Comment by Vanessa219** [comment]
If possible, welcome to add Korean.
