### ISSUE TITLE
how to build the release file.

### ISSUE THREAD

**Issue by jakekwak** [88250/liandi#60]
When I execute `./build.sh` at mac, I got the below error.
I want to make the release file. (zip or dmg)
thanks.

![Screen Shot 2020-05-15 at 12 12 33 AM](https://user-images.githubusercontent.com/15811943/82013884-0807f000-9641-11ea-8ee6-2d25527ab802.png)

**Comment by Vanessa219** [comment]
rm app/node_modules and update app/package.json
```
"dist": "electron-builder"
```
tyr again.

**Comment by jakekwak** [comment]
I think same error.
![Screen Shot 2020-05-15 at 1 08 18 AM](https://user-images.githubusercontent.com/15811943/82017374-9df34900-9648-11ea-8a34-6ebb331f8f14.png)

**Comment by Vanessa219** [comment]
pls try it:
```
cd app & npm run dist
```
what's the version of your node?

**Comment by jakekwak** [comment]
Sorry about that. I changed to new node version.  thanks.
