### ISSUE TITLE
文件结构全面迁移至 TextBundle

### ISSUE THREAD

**Issue by HaujetZhao** [88250/liandi#61]
一直以来，md 文档插入图片都是问题：

用图床链接，不稳定

用本地文件链接，容易丢

这也是我在用 md 做记录时候的烦恼。

不过，Marked 开发者和 Ulysses 团队开发出了一种解决方法，就是 TextBundle，简要解释一下，它是这样的结构：

一个叫 文档.textbundle 的文件夹，内包含：

*  一个 assets 文件夹，用于存放图片等附件
*  一个 info.json 文件，用于存放相关的元数据
* 一个 text.md 文件，用于存放文档内容。文档通过相对路径引用 assets 文件夹内的图片和其它媒体文件。

可以实现一个文包内，既包含 md 文档，也包含图片，预览时无需询问权限，同时又方便直接编辑，非常便捷。

每一个文档都存储在一个 textbundle 中，这样，即便导出，复制到其它设备、平台上，都可以用各种 markdown 编辑器打开文档，正常浏览里面的图片。

Ulysses, Bear这样的流行的写作工具，甚至是Mindnode等思维导图工具，都支持 textbundle。

如果支持textbundle格式。那么我们在快速写作的时候，就可以更加安心。因为我们确认所有的创作内容都可以方便导出带格式、带图片资源版本，轻松在其他专用工具中进一步加工。

这里是 TextBundle 的 [官网](http://textbundle.org) 和 [详细细节](http://textbundle.org/spec)

（同功能请求也在 Vditor 中[提出](https://github.com/Vanessa219/vditor/issues/436)）

**Comment by 88250** [comment]
经过讨论，暂定如下设计：

> 什么 json 魔法也不去管了，直接暴力地只支持 text.md ，
如果文件名字符串匹配 `*.textbundl`，则直接打开里面的 text.md ，如果不匹配，则列出文件列表。
>
>粘贴图片也是，直接一个规则：复制到 assets 文件夹

**Comment by 88250** [comment]
* 对于已有文档，自动创建 xxx.md 文件的父目录 xxx.textbundle，重命名 xxx.md 为 text.md，生成 info.json 和 assets 目录，并将 text.md 中关联的本地图片移动到 assets 目录下同时修改 md 中的引用路径
* 新建文档时创建 TextBundle 结构
* 导航部分隐藏 .textbundle 目录层级，直接显示文档名

此次更新后，将通过 TextBundle 规范强制固化文件结构，不支持 raw.md。

**Comment by 88250** [comment]
上面我说的解决方案还是不太合理。因为不是所有用户都想建立这个文件结构，这样定死的话会有问题。比较稳妥的方案还是在设置-图片里加入类似 typora 的那些配置，拷贝图片时默认复制到文档同级目录，可以指定为自定义目录。

底层结构还是尽量保持用文件系统的直观形式。后面单独做支持 TextBundle 导出的功能，参见 https://github.com/88250/liandi/issues/187。
