### ISSUE TITLE
自动回填 WebDAV 已填参数

### ISSUE THREAD

**Issue by jakekwak** [88250/liandi#65]
![vditor64](https://user-images.githubusercontent.com/15811943/83317490-b2137a80-a1f2-11ea-82a6-7cc3cfb345e4.gif)

**Comment by 88250** [comment]
暂时不考虑了，因为在配置文件中保存密码有点不够安全。

**Comment by jakekwak** [comment]
Is it remember the URL & Username except `Password`.  and  URL history I accessed.

When can I test the latest version?  I want to make the korean version also.

Thanks

**Comment by 88250** [comment]
@jakekwak Recently, we totally rewrite it, you could test it after v1.1.6 released.
