### ISSUE TITLE
编辑器插入文件时的检查问题

### ISSUE THREAD

**Issue by HaujetZhao** [88250/liandi#67]
目前拖入视频的时候是默认上传到 B3log ，而不是复制到同级文件夹。作为一个本地文档编辑、管理工具，理论上最好是先把所有拖入的附件都放到 assets 文件夹，等要发布博客的时候，再上传，并且将上传的文章的附件链接进行自动替换。

今天测试了下，用 HTML 标记（如下述），插入了一个 assets 文件夹的视频（同级目录，相对路径），但是却没能成功播放，可能有点问题。

```
<video src="assets/video.mkv"></video>
```

**Comment by 88250** [comment]
你是在链滴笔记中使用还是在 Solo 中使用上传？Solo 的话是默认集成了社区对象存储服务，链滴笔记目前对于插入文件的处理是放到 md 文件同级目录下，后续会改为 assets 文件夹。

**Comment by JackalZhao** [comment]
> 你是在链滴笔记中使用还是在 Solo 中使用上传？Solo 的话是默认集成了社区对象存储服务，链滴笔记目前对于插入文件的处理是放到 md 文件同级目录下，后续会改为 assets 文件夹。

链滴笔记。我拖入了一个视频到编辑框，提示视频的大小超过10 MB ，表明它是要上传，并且 在上传前要先检查一下视频大小。

**Comment by 88250** [comment]
不会上传的，链滴笔记现在还没有对社区进行集成，这是 v2 的计划，集成社区第一步是要做身份登录验证，和社区账号进行关联。

检查大小估计是编辑器配置了大小限制 @Vanessa219
