### ISSUE TITLE
链滴中点击大纲中的标题，编辑器正文和预览无法跳转到相应位置

### ISSUE THREAD

**Issue by HaujetZhao** [88250/liandi#68]

**Comment by miss-fang** [comment]
同样遇到这个问题

**Comment by TobiasTao** [comment]
+1， 可能是因为  `<webview>` 的原因，在 vscode 的 [webview ](https://code.visualstudio.com/api/extension-guides/webview)中使用 vditor ， 大纲的导航同样失效。

TobiasTao/vscode-md#4
