### ISSUE TITLE
全屏编辑模式下，无法在顶部拖动窗口

### ISSUE THREAD

**Issue by miss-fang** [88250/liandi#70]
见标题。
另外还有一个问题：使用Ctrl+Z后退一步时，不知道后退了我多少步，也不能恢复了，我重新编辑了很多公式。
还有，其他人也反映大纲无法链接到具体位置。

**Comment by miss-fang** [comment]
再报告一个，两次shift调出设置界面，这个快捷键真的不友好，比如我想先切换到英文输入法，再插入公式，那么第一次shift切换到英文，第二次输入$也要用shift，经常不小心就调出设置界面了。

**Comment by 88250** [comment]
撤销的问题麻烦说下重现步骤；Shift 设置稍后继续优化，感谢反馈！

**Comment by miss-fang** [comment]
> 
> 
> 撤销的问题麻烦说下重现步骤；Shift 设置稍后继续优化，感谢反馈！

我不太记得了，只记得有次按Ctrl+Z后，一大堆文字和公式就没了

**Comment by 88250** [comment]
好的， 稍后我们再排查一下，谢谢。

**Comment by 88250** [comment]
撤销的问题现在应该已经修复，UI 方面我们正在重写，等发布新版以后欢迎再试用，谢谢。
