### ISSUE TITLE
【求助】electron + vditor 中 cdn的配置问题

### ISSUE THREAD

**Issue by TobiasTao** [88250/liandi#71]
我在electron中想使用vditor渲染markdown：
![image](https://user-images.githubusercontent.com/37654563/83987056-840c0400-a971-11ea-8756-e38d626a43f9.png)
其中 appPath = app.getAppPath(), 但是出现了错误：
![image](https://user-images.githubusercontent.com/37654563/83987124-cd5c5380-a971-11ea-963d-e142c0cbdfb0.png)
这个文件路径是正确的。
我的 BrowserWindow选项：
```
    webPreferences: {
      nodeIntegration: true,
      allowRunningInsecureContent: true,
      webSecurity: false,
    },
```
请问一下 @88250 大大有没有碰到过？

**Comment by Vanessa219** [comment]
你可以跟踪一下 app/src/editors/webview.ts 中的 cdn 配置
