### ISSUE TITLE
Web GUI Server

### ISSUE THREAD

**Issue by HaujetZhao** [88250/liandi#72]
### 你在什么场景下需要该功能？

想在移动端（手机端、平板端、总之是另外一台设备）上访问、浏览、编辑电脑上的 MarkDown 文档时。

### 描述可能的解决方案

链滴笔记启动后，可以选择启动一个后台的 Web GUI Server，端口例如 8080，在其它设备（例如平板、手机）上通过浏览器访问 `http://computer_host:8080` 来查看电脑上链滴笔记已挂载目录的笔记，还可以直接用 Vditor 网页端编辑。

这样 Vditor 作为网页端 MD 编辑器的作用真是发挥到极致了。链滴笔记以后也就不用考虑移动平台了，毕竟只要在一个设备上运行服务端，网页端就可以覆盖局域网下所有的设备了。同时，其它所有设备也不用安装额外的软件，不用担心同步的问题，直接通过浏览器访问自己的笔记，一端笔记，多端共享。

### 其他信息

需要不少前端、后端的工作。可能属于 V2 阶段的需求。先提出来，说不定能作为 V2.0 的 milestone。

**Comment by 88250** [comment]
在桌面运行着一般来说就不会又在其他设备上使用了吧，除了用 PC 做 Server 的用法。链滴笔记目前主要还是聚焦于桌面端开发，其他端要等以后再考虑了，感谢。
