### ISSUE TITLE
文件树上下双栏布局

### ISSUE THREAD

**Issue by HaujetZhao** [88250/liandi#74]
### 你在什么场景下需要该功能？

要看大纲的时候

### 描述可能的解决方案

在链滴笔记上，三栏设计很棒，不过在打开大纲或双栏编辑的时候，整个屏幕变成四栏，就会很挤。虽然可以切换到全屏，但是，如果能有个方案，改善下三栏排版，不全屏就解决布局问题，那是最好的。

刚刚看到一个开源 md 笔记 VNOTE，下载下来以后，看到他的布局有很多可以参考的地方，例如：

![image](https://user-images.githubusercontent.com/19181833/84843412-6712b780-b07a-11ea-9fb5-2121b03dee2a.png)

这个左侧的上下双栏设计真是深得我心啊！

这个左侧的上下双栏设计真是深得我心啊！

这个左侧的上下双栏设计真是深得我心啊！

![image](https://user-images.githubusercontent.com/19181833/84843481-945f6580-b07a-11ea-88bf-06da0176f2f3.png)

### 描述你认为的候选方案

或许，链滴笔记的文件夹框，可以做到左边第一栏，用上下双栏的结构来显示挂载文件夹（上栏）和子文件及文件夹（下栏），第二栏用于显示大纲，第三栏用于显示笔记。

更激进的话，就是每一栏都做成大型软件的栏那样，可以吸附、解吸附，随意调整，示意图如下：

![image](https://user-images.githubusercontent.com/19181833/84843835-8f4ee600-b07b-11ea-9991-57ca76e478b9.png)

![image](https://user-images.githubusercontent.com/19181833/84843846-970e8a80-b07b-11ea-8a6a-70c81c8d1d4f.png)

![image](https://user-images.githubusercontent.com/19181833/84843859-a097f280-b07b-11ea-8093-11b870a6f1af.png)

比如在链滴笔记里就可以把第二栏拖到第一栏下边，变成上下双栏，或者把大纲栏拖到右侧。

### 其他信息

想法是好的，就是实施起来可能很难吧。

**Comment by 88250** [comment]
感谢反馈，上下栏的设计确实不错，等后续有时间再改改，现在主要任务是优化编辑器。

**Comment by 88250** [comment]
UI 方面暂时不做大调整了，感谢反馈。
