### ISSUE TITLE
快捷笔记

### ISSUE THREAD

**Issue by HaujetZhao** [88250/liandi#75]
有些东西想记下来，很急地记下来，来不及去新建文档，起文档名，就只想抓起一张草稿纸，赶紧把这点东西记下来。过会再处理保存到哪里。

灵犀页，就是个独立于任何笔记的临时笔记页。可以一键打开，可以用于粘贴些临时灵感、素材

目前，我是使用 notepad++ 作为临时灵犀页用，通过快捷键打开。

如果笔记软件能支持这样打开方式固定的临时笔记页的话，还是很有用的。

**Comment by 88250** [comment]
等[块级引用](https://github.com/88250/liandi/issues/87)实现后，可能会引入 Daily Notes 的用法，每天用日期作为名称创建一个空的文档。

**Comment by jazzson** [comment]
这个很实用！ 期待中

**Comment by 88250** [comment]
目前已经支持 Ctrl+n 快捷键创建文档。
