### ISSUE TITLE
窗体整体动态布局特性和带来的 feature

### ISSUE THREAD

**Issue by HaujetZhao** [88250/liandi#76]
等 Vditor 搞好了，链滴笔记重构的时候搞 😂

在聊天室提出来的。

<video controls="controls" src="https://b3logfile.com/file/2020/06/20200617104338-1e1efc4f.mp4" class="vsc-initialized" data-vscid="cz5ssxm7f" __idm_id__="745635842"></video>

视频地址：https://b3logfile.com/file/2020/06/20200617104338-1e1efc4f.mp4

**Comment by 88250** [comment]
感谢反馈，UI 方面暂时保持简洁。
