### ISSUE TITLE
BugReport: jump out code block , can't input chinese word

### ISSUE THREAD

**Issue by laoLiangLoveProgram** [88250/liandi#84]
# 描述问题
> 出代码块后, 输入1次回车, 跳到本层列表, 再输入一次回车, 跳到上层列表, 此时输入文字, 无法直接输入, 会跳回代码块, 必须先输入数字, 然后才能输入文本
# 期待的结果
> 不论往上跳几层, 输入文字应该不应该回跳
# 截屏或录像
![bug](https://user-images.githubusercontent.com/25242107/87289977-f606d880-c52f-11ea-8328-27660e57d8f3.gif)

**Comment by 88250** [comment]
感谢反馈，这个问题会在 Vditor 编辑器项目中进行修复。
