### ISSUE TITLE
链滴在 Linux 下如何安装, 小白一枚, 看了 readme.md 也不知道怎么装.

### ISSUE THREAD

**Issue by kuleyu** [88250/liandi#85]
Ubantu OS, 从 release 页面下载的 `liandi-1.1.2-linux.tar.gz` 包, 一般安装 `.tar.gz` 用下面这种步骤就可以了:
1. `tar zxvf liandi-1.1.2-linux.tar.gz`
2. `cd liandi-1.1.2-linux`
3. `./configure`（有的版本无此命令，则可跳过这一步骤）
4. `make`
5. `make install`

然而这里不行, 所以想请教下该怎么安装.

或者有的也会针对 linux 提供 AppImage 包, 直接双击就可以运行了. 不知之后是否会提供 AppImage 包.

**Comment by 88250** [comment]
你好，解压以后 ./liandi 就可以执行。

**Comment by kuleyu** [comment]
谢谢!
