### ISSUE TITLE
引入内容块（Block）和内容块引用（Block Reference）

### ISSUE THREAD

**Issue by 88250** [88250/liandi#87]
### 内容块交互

* 每个块级节点都带有 id，标题是内容块，整个文档也是内容块，用块的概念架构所有内容
* 通过 `((id))` 可以引用内容块，打出 `((` 后弹出块筛选框进行选择
* 内容块可以获取反向链接（被引用）列表
* 根据内容块之间的引用关系生成图谱

### 内容块引用语法

* `((id))` 点击跳转到定义块，使用 id 作为锚文本
* `((id "text"))` 显示定义锚文本

#### UI

* [x] 新增 Vditor 块模式
* [x] 按键输入自动完成弹框下拉选择
* [x] 内容块 ID 合并
* [x] 查看链接关系
* [x] 查看关系图

#### 内核

* [x] [支持内容块引用语法](https://github.com/88250/lute/issues/82)
* [x] [支持结构化 JSON 渲染](https://github.com/88250/liandi/issues/89)
* [x] 启动时将文档解析生成的 Markdown AST 常驻内存
* [x] 根据用户输入更新 AST 并持久化到磁盘 ast.json，下次启动优先使用 ast.json 构建 AST
* [x] 查询给定关键字的内容块引用
* [x] 反向链接查询
* [x] 构建关系图

#### 

#### 待定需求

* 多开时文件树、编辑器内容等状态的同步
* 内容块支持定义别名（id-alias）列表，方便导出可读，同时可以用于支持同/近义词
* 提供导出选项（内容块引用处嵌入全文、摘要或别名）
* 监听文件变化实现实时导入和索引更新

#### 待优化

* 性能优化：启动索引、内容块查询、反向链接查询、关系图生成

---

下面内容是链滴笔记特性随记。

## 标准 Markdown

完整实现 GFM（GitHub Flavored Markdown）规范，这意味着链滴笔记具有良好的兼容性，让笔记能够在最大程度上通用。

## 块级引用

支持 `((id))` 来引用其他 Markdown 块级元素（包括标题、段落、代码块、列表、块引用等），将卡片式双向链接和 Markdown 进行了语义层面的深度融合。

## 即时渲染

支持类似 Typora 的编辑模式，仅在光标所在元素展开 Markdown 标记符，在方便 Markdown 排版的同时也能让使用者将注意力集中在内容上。

## 离线可用

可以在离线断网的情况下使用，笔记数据完全保存在用户本地磁盘。笔记数据使用人类可读的 JSON 格式保存，使用过程中自动实时导出 Markdown 文件。

另外，链滴笔记也支持 WebDAV 协议，在用法上和打开本地目录几乎一致，为用户同步数据多一种选择。

## 开源

链滴笔记是开源的，核心部分均是我们从零编写：

* 链滴笔记应用：https://github.com/88250/liandi
* Vditor 编辑器：https://github.com/Vanessa219/vditor
* Markdown 引擎：https://github.com/88250/lute

## 技术架构

* 基于 B/S 模式，内核进程作为服务端，通过 WebSocket 和 Electron UI 进程通讯
* 内核进程通过 Electron 首次启动拉起，后面的多 UI 窗口进程通过内核拉起
* 后续将支持浏览器内直接使用，这样能极大丰富使用场景（比如远程访问、多端适配和同步等）
* 不内建插件体系，而是直接使用浏览器插件，API 已由内核提供

**Comment by ffywhxf** [comment]
请问怎么使用？输入 (( 没反应。

**Comment by Vanessa219** [comment]
现在还在开发中，预计下周发布。最终效果可看一下 https://liandi.b3log.org
