### ISSUE TITLE
有没有增加 vim 键盘映射的开发计划？

### ISSUE THREAD

**Issue by HackerXiang** [88250/liandi#90]
### 你在什么场景下需要该功能？

平时习惯用 vim 的按键模式写代码，代码和笔记经常换来换去，键盘按键容易出错

### 描述可能的解决方案

额外增加一个 vim 模式的按键支持

### 描述你认为的候选方案

类似 vscode 那样，安装一个 vim 插件之后就可以无缝切换了

### 其他信息

无

**Comment by 88250** [comment]
抱歉，暂时没有。以后如果有会重开这个 issue，感谢反馈。
