### ISSUE TITLE
内容块嵌入渲染

### ISSUE THREAD

**Issue by 88250** [88250/liandi#95]
`((id "*"))` 原地嵌入源块完整内容渲染

其他优化建议：

![5A87__}C1L 58C3OIOAN86Y](https://user-images.githubusercontent.com/873584/90302440-c2c1bb80-ded8-11ea-8b17-ac04f34f163c.png)

**Comment by lyslives** [comment]
我下的群里最新2020-8-15 V1.1.3 win10 还是没渲染好呢？【1 】  `内容`  会丢失。【2】 能不能与ob一样所见即所得，而不是文本格式
 https://cdn.jsdelivr.net/gh/lyslives/pic/lyslives/pic/herbal/mmexport1597444126466.jpg

**Comment by 88250** [comment]
@lyslives 感谢反馈，将在 https://github.com/88250/liandi/issues/119 中改进。
